repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.44.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args: ['--envs=AWS_DEFAULT_REGION="us-east-1"']
      - id: terraform_tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args: [ --branch, develop, --branch, main, --branch, release ]
